### ISSUE TITLE
transitive raw resource dependency

### ISSUE THREAD

**Issue by laverite** [basho/rebar_raw_resource#1]
hi.  is this plugin capable of working transitively?  i have the following:

depA --> depB --> depC(raw)

where depB wraps depC as a raw dependency via the plugin.

`{deps,[
  {depC,
    {raw,
      {git, "git@...",
        {branch, "master"}
   }}}
]}.`

Running rebar from depB runs fine.  However if I add another layer of dependency (depA) and try to run rebar from depA, then I get an error.

> escript: exception error: no function clause matching  
>                  rebar_fetch:format_error({error,  
>                                            "{rebar_raw_resource,unmapped_spec,\n                    \"git@...\"}"})

**Comment by tburghart** [comment]
Where is the `plugins` clause for `rebar_raw_resource` - in rebar.config of `depA`, `depB`, or both?

The plugin is obviously loaded, because that's where the error is coming from, but it apparently has not seen the `depC` spec in the intermediate config.

This isn't a scenario I've tested explicitly yet, but I have an idea what may be going on, and it appears to expose an unhanded error case as well.

**Comment by laverite** [comment]
The plugins clause was only given in B's rebar.config in the scenario above.  

If I include the plugin as well as depC as a raw dependency in A's rebar.config, then it seems to work since it has visibility to depC.

**Comment by tburghart** [comment]
@laverite The `develop` branch of the plugin _should_ work in all cases now.

If you're able to try it, especially in all of your possible use cases, it'd be appreciated.

**Comment by tburghart** [comment]
Fixed and merged to the master branch.

**Comment by laverite** [comment]
sorry didn't have time to check this out till now.  works for me, but i had to still include the plugin in the parent rebar config, but that's fine.  thanks for the fix!

**Comment by coolchevy** [comment]
@tburghart checked in master/develop branches. Issue has still present
Could you fix this?
